(in-package :stumpwm)

(setf *maxsize-border-width* 1)
(setf *transient-border-width* 1)
(setf *normal-border-width* 1)
(setf *window-border-style* :thick)
(setf *float-window-title-height* 5)
(setf *float-window-border* 5)
(set-win-bg-color "#ef708e")
(set-focus-color   "#fbc6d2")
(set-unfocus-color "#ef708e")
(set-float-focus-color   "#fbc6d2")
(set-float-unfocus-color "#ef708e")
(set-normal-gravity :center)
(set-maxsize-gravity :center)
(gravity :center)
