(in-package :stumpwm)

(setf *maxsize-border-width* 1)
(setf *transient-border-width* 1)
(setf *normal-border-width* 1)
(setf *window-border-style* :thick)
(setf *float-window-title-height* 8)
(setf *float-window-border* 0)
(set-win-bg-color  *win-bg-color*)
(set-focus-color   *focus-color*)
(set-unfocus-color *unfocus-color*)
(set-float-focus-color   *float-focus-color*)
(set-float-unfocus-color *float-unfocus-color*)
(set-normal-gravity :center)
(set-maxsize-gravity :center)
(gravity :center)

(defun reorder-windows-handler (win)
  (let* ((group-windows (group-windows (current-group)))
         (sorted-windows (if (find win group-windows)
                             (append (remove win (sort-windows group-windows)) (list win))
                             (sort-windows group-windows))))
    (do ((num 1 (+ num 1))
         (windows sorted-windows (cdr windows)))
        ((null (car windows)))
      (setf (window-number (car windows)) num))))

(add-hook *new-window-hook* 'reorder-windows-handler)
(add-hook *destroy-window-hook* 'reorder-windows-handler)
