(in-package :stumpwm)

(setf *maxsize-border-width* 1)
(setf *transient-border-width* 1)
(setf *normal-border-width* 1)
(setf *window-border-style* :thick)
(set-win-bg-color "Gray20")
(set-focus-color   "Gray100")
(set-unfocus-color "Gray20")
(set-float-focus-color   "Gray100")
(set-float-unfocus-color "Gray20")
(set-normal-gravity :center)
(set-maxsize-gravity :center)
(gravity :center)
